<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Company>Cedric-Belin.fr</Company>
		<Copyright>© Cédric Belin</Copyright>
		<Description>Web component library by Cédric Belin, full stack developer.</Description>
		<Product>Belin UI</Product>
		<Version>0.31.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>Belin.UI</AssemblyName>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
		<HotReloadAutoRestart>true</HotReloadAutoRestart>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutDir>../../Binaries</OutDir>
		<RootNamespace>Belin.UI</RootNamespace>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>
</Project>
